
// 1. **Reversing a String**:
//     Write a function that takes a string as input and returns the string reversed.

let str = "Hello Programmers";
let reversedStr = str.split('').reverse().join('');
console.log(reversedStr);


// split(''): This method splits the string into an array of individual characters.
// reverse(): This method reverses the elements in the array.
// join(''): This method joins the elements of the array back into a single string.

//-----------------------------------------------------------------------------------------------------------



// 2. **Palindrome Check**:
//     Write a function to check if a given string is a palindrome (a string that reads the same forwards and backwards).

let reverse = str.split('').reverse().join('');
    
// Check if the original string is equal to the reversed string
result = str === reverse;
console.log(result);


//----------------------------------------------------------------------------------------------------------------






// 3. **Anagram Check**:
//     Write a function to determine if two strings are anagrams of each other (contain the same characters in different orders).

var str1 = "Pale";
var str2 = "apple";
str1 = str.split('').sort().join('');
str2 = str.split('').sort().join('');

Anagram = str1 === str2;
console.log(Anagram);

//-------------------------------------------------------------------------------------------------------------------


// 4. **Character Frequency Count**:
//     Write a function that takes a string and returns a dictionary with the frequency count of each character in the string.


let str3 = "Hi , My  name is  Ayesha Nudrat ";

let freqCount = {};

    for (let char of str3) {
        if (freqCount[char]) {
            freqCount[char] += 1;
        } else {
            freqCount[char] = 1;
        }
    }

    console.log (freqCount);

    //--------------------------------------------------------------------------------------------------------------



// 5. **First Non-Repeating Character**:
//     Write a function that takes a string and returns the first non-repeating character in the string.


function firstNonRepeatingChar(str) {

    let  character = "3 ,4,6,8,4,3,2,3,5,3,4,4,4";
    const charCount = {};

  
    // Count the occurrences of each character
    for (const char of str) {
      charCount[char] = (charCount[char] || 0) + 1;
    }
  
    // Find the first   
   
    for (const char of str) {
      if (charCount[char] === 1) {
        return char;
      }
    }
  
    // If no non-repeating character found, return null or an empty string
    return null; // or return '';
  }

  //---------------------------------------------------------------------------------------------------------

// 6. **String Compression**:
//     Write a function that compresses a string using the counts of repeated characters. For example, the string "aabcccccaaa" would become "a2b1c5a3".

// 7. **Rotate String**:
//     Write a function to rotate a given string to the right by a specified number of characters. For example, rotating "hello" by 2 characters would result in "lohel".

// 8. **Longest Substring Without Repeating Characters**:
//     Write a function that finds the length of the longest substring without repeating characters in a given string.

// 9. **Count and Say**:
//     Write a function to generate the nth term of the count-and-say sequence. The count-and-say sequence is a sequence of digit strings defined by the recursive formula: "1" is the first term, and each subsequent term is generated by describing the previous term.

// 10. **Permutations of a String**:
//     Write a function to generate all permutations of a given string.

